// ============================================================
// LLM GUARD v3 - Content Script
// Patterns: hand-crafted originals + auto-generated from
//           gitleaks.toml (run `node generate-patterns.js` to refresh)
// ============================================================

// ------------------------------------------------------------------
// SECTION 1: Original hand-crafted patterns 
// These are kept as the primary source — more readable & tuned for
// the LLM-chat context (e.g. .env pastes, generic secret= patterns).
// ------------------------------------------------------------------
const ORIGINAL_PATTERNS = [
  { name: "OpenAI API Key",               regex: /sk-[a-zA-Z0-9\-_]{20,80}/,                          severity: "critical" },
  { name: "OpenAI Org ID",                regex: /org-[a-zA-Z0-9]{20,40}/,                            severity: "high"     },
  { name: "AWS Access Key ID",            regex: /AKIA[0-9A-Z]{16}/,                                   severity: "critical" },
  { name: "Google API Key",               regex: /AIza[0-9A-Za-z\-_]{35}/,                            severity: "critical" },
  { name: "Google OAuth Token",           regex: /ya29\.[0-9A-Za-z\-_]+/,                             severity: "critical" },
  { name: "GCP Service Account",          regex: /"type":\s*"service_account"/,                       severity: "critical" },
  { name: "Azure Storage Key",            regex: /AccountKey=[a-zA-Z0-9+\/=]{60,}/,                   severity: "critical" },
  { name: "GitHub PAT (classic)",         regex: /ghp_[a-zA-Z0-9]{36}/,                               severity: "critical" },
  { name: "GitHub OAuth Token",           regex: /gho_[a-zA-Z0-9]{36}/,                               severity: "critical" },
  { name: "GitHub App Token",             regex: /ghs_[a-zA-Z0-9]{36}/,                               severity: "critical" },
  { name: "GitHub Fine-grained Token",    regex: /github_pat_[a-zA-Z0-9_]{82}/,                       severity: "critical" },
  { name: "Anthropic API Key",            regex: /sk-ant-[a-zA-Z0-9\-_]{50,}/,                        severity: "critical" },
  { name: "Stripe Secret Key (live)",     regex: /sk_live_[0-9a-zA-Z]{24,}/,                          severity: "critical" },
  { name: "Stripe Secret Key (test)",     regex: /sk_test_[0-9a-zA-Z]{24,}/,                          severity: "high"     },
  { name: "Stripe Restricted Key",        regex: /rk_live_[0-9a-zA-Z]{24,}/,                          severity: "critical" },
  { name: "SendGrid API Key",             regex: /SG\.[a-zA-Z0-9\-_]{22}\.[a-zA-Z0-9\-_]{43}/,        severity: "critical" },
  { name: "Slack Bot Token",              regex: /xoxb-[0-9]{6,}-[0-9]{6,}-[a-zA-Z0-9]{24}/,          severity: "critical" },
  { name: "Slack User Token",             regex: /xoxp-[0-9]+-[0-9]+-[0-9]+-[a-zA-Z0-9]+/,            severity: "critical" },
  { name: "Slack Webhook URL",            regex: /hooks\.slack\.com\/services\/T[a-zA-Z0-9_]+/,        severity: "high"     },
  { name: "Razorpay Key (India)",         regex: /rzp_(live|test)_[a-zA-Z0-9]{14}/,                   severity: "critical" },
  { name: "RSA Private Key",              regex: /-----BEGIN RSA PRIVATE KEY-----/,                    severity: "critical" },
  { name: "Private Key (PEM)",            regex: /-----BEGIN PRIVATE KEY-----/,                        severity: "critical" },
  { name: "EC Private Key",               regex: /-----BEGIN EC PRIVATE KEY-----/,                     severity: "critical" },
  { name: "SSH Private Key",              regex: /-----BEGIN OPENSSH PRIVATE KEY-----/,                severity: "critical" },
  { name: "JWT Token",                    regex: /eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}/, severity: "high" },
  { name: "Secret/API key in code",       regex: /(secret|api_key|apikey|api-key|auth_token|access_token)\s*[=:]\s*['"`][a-zA-Z0-9\-_\/+.]{12,}['"`]/i, severity: "high" },
  { name: "MongoDB Connection String",    regex: /mongodb(\+srv)?:\/\/[^:]+:[^@]+@/,                  severity: "critical" },
  { name: "PostgreSQL Connection String", regex: /postgresql?:\/\/[^:]+:[^@]+@/,                      severity: "critical" },
  { name: "MySQL Connection String",      regex: /mysql:\/\/[^:]+:[^@]+@/,                            severity: "critical" },
  { name: ".env file content",            regex: /^(OPENAI|AWS|STRIPE|SECRET|API_KEY|DATABASE_URL|TOKEN)[_A-Z]*\s*=\s*.{8,}$/m, severity: "high" },
];

// ------------------------------------------------------------------
// SECTION 2: Auto-generated patterns from gitleaks.toml
// Generated by: node generate-patterns.js
// Refresh anytime: node generate-patterns.js  (fetches latest TOML)
// ------------------------------------------------------------------
const GITLEAKS_PATTERNS = [
  { name: "1Password Secret Key",                  id: "1password-secret-key",                  regex: new RegExp("\\bA3-[A-Z0-9]{6}-(?:(?:[A-Z0-9]{11})|(?:[A-Z0-9]{6}-[A-Z0-9]{5}))-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}\\b", "i"), severity: "critical" },
  { name: "1Password Service Account Token",       id: "1password-service-account-token",       regex: new RegExp("ops_eyJ[a-zA-Z0-9+/]{250,}={0,3}", "i"), severity: "critical" },
  { name: "Anthropic Admin API Key",               id: "anthropic-admin-api-key",               regex: new RegExp("\\b(sk-ant-admin01-[a-zA-Z0-9_\\-]{93}AA)\\b", "i"), severity: "critical" },
  { name: "Anthropic API Key (strict)",            id: "anthropic-api-key",                     regex: new RegExp("\\b(sk-ant-api03-[a-zA-Z0-9_\\-]{93}AA)\\b", "i"), severity: "critical" },
  { name: "AWS Access Token",                      id: "aws-access-token",                      regex: new RegExp("\\b((?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z2-7]{16})\\b", "i"), severity: "critical" },
  { name: "Azure AD Client Secret",                id: "azure-ad-client-secret",                regex: new RegExp("[a-zA-Z0-9_~.]{3}\\dQ~[a-zA-Z0-9_~.-]{31,34}", "i"), severity: "critical" },
  { name: "Databricks API Token",                  id: "databricks-api-token",                  regex: new RegExp("\\b(dapi[a-f0-9]{32}(?:-\\d)?)\\b", "i"), severity: "critical" },
  { name: "DigitalOcean Access Token",             id: "digitalocean-access-token",             regex: new RegExp("\\b(doo_v1_[a-f0-9]{64})\\b", "i"), severity: "critical" },
  { name: "DigitalOcean Personal Access Token",    id: "digitalocean-pat",                      regex: new RegExp("\\b(dop_v1_[a-f0-9]{64})\\b", "i"), severity: "critical" },
  { name: "DigitalOcean Refresh Token",            id: "digitalocean-refresh-token",            regex: new RegExp("\\b(dor_v1_[a-f0-9]{64})\\b", "i"), severity: "critical" },
  { name: "Doppler API Token",                     id: "doppler-api-token",                     regex: new RegExp("dp\\.pt\\.[a-z0-9]{43}", "i"), severity: "critical" },
  { name: "Dynatrace API Token",                   id: "dynatrace-api-token",                   regex: new RegExp("dt0c01\\.[a-z0-9]{24}\\.[a-z0-9]{64}", "i"), severity: "critical" },
  { name: "Facebook Page Access Token",            id: "facebook-page-access-token",            regex: new RegExp("\\b(EAA[MC][a-z0-9]{100,})\\b", "i"), severity: "high" },
  { name: "Fly.io Access Token",                   id: "flyio-access-token",                    regex: new RegExp("\\b(fo1_[\\w-]{43})\\b", "i"), severity: "high" },
  { name: "GCP API Key",                           id: "gcp-api-key",                           regex: new RegExp("\\b(AIza[\\w-]{35})\\b", "i"), severity: "critical" },
  { name: "GitHub App Token",                      id: "github-app-token",                      regex: new RegExp("(?:ghu|ghs)_[0-9a-zA-Z]{36}", "i"), severity: "critical" },
  { name: "GitHub Fine-Grained PAT",               id: "github-fine-grained-pat",               regex: new RegExp("github_pat_\\w{82}", "i"), severity: "critical" },
  { name: "GitHub OAuth Token",                    id: "github-oauth",                          regex: new RegExp("gho_[0-9a-zA-Z]{36}", "i"), severity: "critical" },
  { name: "GitHub PAT",                            id: "github-pat",                            regex: new RegExp("ghp_[0-9a-zA-Z]{36}", "i"), severity: "critical" },
  { name: "GitHub Refresh Token",                  id: "github-refresh-token",                  regex: new RegExp("ghr_[0-9a-zA-Z]{36}", "i"), severity: "critical" },
  { name: "GitLab PAT",                            id: "gitlab-pat",                            regex: new RegExp("glpat-[\\w-]{20}", "i"), severity: "critical" },
  { name: "GitLab Pipeline Trigger Token",         id: "gitlab-ptt",                            regex: new RegExp("glptt-[0-9a-f]{40}", "i"), severity: "critical" },
  { name: "GitLab Runner Registration Token",      id: "gitlab-rrt",                            regex: new RegExp("GR1348941[\\w-]{20}", "i"), severity: "critical" },
  { name: "Grafana API Key",                       id: "grafana-api-key",                       regex: new RegExp("\\b(eyJrIjoi[A-Za-z0-9]{70,400}={0,3})\\b", "i"), severity: "high" },
  { name: "Grafana Cloud API Token",               id: "grafana-cloud-api-token",               regex: new RegExp("\\b(glc_[A-Za-z0-9+/]{32,400}={0,3})\\b", "i"), severity: "high" },
  { name: "Grafana Service Account Token",         id: "grafana-service-account-token",         regex: new RegExp("\\b(glsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8})\\b", "i"), severity: "high" },
  { name: "HashiCorp Terraform API Token",         id: "hashicorp-tf-api-token",                regex: new RegExp("[a-z0-9]{14}\\.atlasv1\\.[a-z0-9\\-_=]{60,70}", "i"), severity: "critical" },
  { name: "HashiCorp Vault Batch Token",           id: "vault-batch-token",                     regex: new RegExp("b\\.AAAAAQ[0-9a-zA-Z_-]{50}", "i"), severity: "critical" },
  { name: "HashiCorp Vault Service Token",         id: "vault-service-token",                   regex: new RegExp("hvs\\.[0-9A-Za-z_-]{90,100}", "i"), severity: "critical" },
  { name: "Heroku API Key",                        id: "heroku-api-key",                        regex: new RegExp("heroku.{0,30}[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", "i"), severity: "critical" },
  { name: "Hugging Face Access Token",             id: "huggingface-access-token",              regex: new RegExp("\\b(hf_[a-z]{34})\\b", "i"), severity: "high" },
  { name: "Hugging Face Org API Token",            id: "huggingface-organization-api-token",    regex: new RegExp("\\b(api_org_[a-z]{34})\\b", "i"), severity: "high" },
  { name: "Infracost API Token",                   id: "infracost-api-token",                   regex: new RegExp("\\b(ico-[a-zA-Z0-9]{32})\\b", "i"), severity: "high" },
  { name: "JSON Web Token",                        id: "jwt",                                   regex: new RegExp("\\b(ey[a-zA-Z0-9]{17,}\\.ey[a-zA-Z0-9\\/\\\\_-]{17,}\\.(?:[a-zA-Z0-9\\/\\\\_-]{10,}={0,2})?)\\b", "i"), severity: "high" },
  { name: "Linear API Key",                        id: "linear-api-key",                        regex: new RegExp("lin_api_[a-z0-9]{40}", "i"), severity: "high" },
  { name: "Mailchimp API Key",                     id: "mailchimp-api-key",                     regex: new RegExp("[a-f0-9]{32}-us\\d\\d", "i"), severity: "high" },
  { name: "Mailgun Private API Token",             id: "mailgun-private-api-token",             regex: new RegExp("key-[a-f0-9]{32}", "i"), severity: "high" },
  { name: "npm Access Token",                      id: "npm-access-token",                      regex: new RegExp("npm_[a-zA-Z0-9]{36}", "i"), severity: "high" },
  { name: "OpenAI API Key (strict)",               id: "openai-api-key",                        regex: new RegExp("\\b(sk-(?:proj-|None-)?[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20})\\b", "i"), severity: "critical" },
  { name: "PlanetScale API Token",                 id: "planetscale-api-token",                 regex: new RegExp("\\b(pscale_tkn_[a-zA-Z0-9=\\-_.]{32,64})\\b", "i"), severity: "critical" },
  { name: "PlanetScale OAuth Token",               id: "planetscale-oauth-token",               regex: new RegExp("\\b(pscale_oauth_[a-zA-Z0-9=\\-_.]{32,64})\\b", "i"), severity: "critical" },
  { name: "PlanetScale Password",                  id: "planetscale-password",                  regex: new RegExp("\\b(pscale_pw_[a-zA-Z0-9=\\-_.]{32,64})\\b", "i"), severity: "critical" },
  { name: "Postman API Token",                     id: "postman-api-token",                     regex: new RegExp("PMAK-[a-f0-9]{24}-[a-f0-9]{34}", "i"), severity: "high" },
  { name: "Prefect API Token",                     id: "prefect-api-token",                     regex: new RegExp("pnu_[a-z0-9]{36}", "i"), severity: "high" },
  { name: "Private Key (any type)",                id: "privatekey",                            regex: new RegExp("-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY(?: BLOCK)?-----", "i"), severity: "critical" },
  { name: "Pulumi API Token",                      id: "pulumi-api-token",                      regex: new RegExp("pul-[a-f0-9]{40}", "i"), severity: "high" },
  { name: "PyPI Upload Token",                     id: "pypi-upload-token",                     regex: new RegExp("pypi-AgEIcHlwaS5vcmc[a-zA-Z0-9\\-_]{50,1000}", "i"), severity: "high" },
  { name: "Razorpay API Key",                      id: "razorpay-api-key",                      regex: new RegExp("rzp_(?:live|test)_[a-zA-Z0-9]{14}", "i"), severity: "critical" },
  { name: "RubyGems API Token",                    id: "rubygems-api-token",                    regex: new RegExp("rubygems_[a-f0-9]{48}", "i"), severity: "high" },
  { name: "SendGrid API Token",                    id: "sendgrid-api-token",                    regex: new RegExp("SG\\.[a-zA-Z0-9\\-_.]{66}", "i"), severity: "critical" },
  { name: "Sendinblue API Token",                  id: "sendinblue-api-token",                  regex: new RegExp("xkeysib-[a-f0-9]{64}-[a-zA-Z0-9]{16}", "i"), severity: "high" },
  { name: "Shippo API Token",                      id: "shippo-api-token",                      regex: new RegExp("shippo_(?:live|test)_[a-f0-9]{40}", "i"), severity: "critical" },
  { name: "Shopify Access Token",                  id: "shopify-access-token",                  regex: new RegExp("shpat_[a-fA-F0-9]{32}", "i"), severity: "critical" },
  { name: "Shopify Custom Access Token",           id: "shopify-custom-access-token",           regex: new RegExp("shpca_[a-fA-F0-9]{32}", "i"), severity: "critical" },
  { name: "Shopify Private App Access Token",      id: "shopify-private-app-access-token",      regex: new RegExp("shppa_[a-fA-F0-9]{32}", "i"), severity: "critical" },
  { name: "Shopify Shared Secret",                 id: "shopify-shared-secret",                 regex: new RegExp("shpss_[a-fA-F0-9]{32}", "i"), severity: "critical" },
  { name: "Slack App Token",                       id: "slack-app-token",                       regex: new RegExp("xapp-\\d-[A-Z0-9]+-\\d+-[a-z0-9]+", "i"), severity: "critical" },
  { name: "Slack Bot Token",                       id: "slack-bot-token",                       regex: new RegExp("xoxb-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*", "i"), severity: "critical" },
  { name: "Slack Legacy Token",                    id: "slack-legacy-token",                    regex: new RegExp("xox[os]-\\d+-\\d+-\\d+-[a-fA-F\\d]+", "i"), severity: "critical" },
  { name: "Slack User Token",                      id: "slack-user-token",                      regex: new RegExp("xox[pe](?:-[0-9]{10,13}){3}-[a-zA-Z0-9-]{28,34}", "i"), severity: "critical" },
  { name: "Slack Webhook URL",                     id: "slack-webhook-url",                     regex: new RegExp("https://hooks\\.slack\\.com/(?:services|workflows)/T[a-zA-Z0-9_]+/B[a-zA-Z0-9_]+/[a-zA-Z0-9_]+", "i"), severity: "high" },
  { name: "Square Access Token",                   id: "square-access-token",                   regex: new RegExp("sq0atp-[0-9A-Za-z\\-_]{22}", "i"), severity: "critical" },
  { name: "Square OAuth Secret",                   id: "square-secret",                         regex: new RegExp("sq0csp-[0-9A-Za-z\\-_]{43}", "i"), severity: "critical" },
  { name: "Stripe Access Token",                   id: "stripe-access-token",                   regex: new RegExp("(?:r|s)k_(?:live|test|prod|sandbox)_[0-9a-zA-Z]{10,99}", "i"), severity: "critical" },
  { name: "Telegram Bot API Token",                id: "telegram-bot-api-token",                regex: new RegExp("(\\d{8,10}:[a-zA-Z0-9_-]{35})", "i"), severity: "critical" },
  { name: "Twilio API Key",                        id: "twilio-api-key",                        regex: new RegExp("SK[a-z0-9]{32}", "i"), severity: "critical" },
  { name: "Yandex API Key",                        id: "yandex-api-key",                        regex: new RegExp("AQVN[A-Za-z0-9_\\-]{35,38}", "i"), severity: "critical" },
  { name: "Yandex AWS Access Token",               id: "yandex-aws-access-token",               regex: new RegExp("YC[a-zA-Z0-9_\\-]{38}", "i"), severity: "critical" },
];

// ------------------------------------------------------------------
// SECTION 3: Merge — originals take precedence, gitleaks fills gaps
// Deduplication: skip gitleaks patterns whose regex source overlaps
// with an already-registered original (matched by prefix keyword).
// ------------------------------------------------------------------
const ORIGINAL_PREFIXES = new Set(
  ORIGINAL_PATTERNS.map(p => p.regex.source.slice(0, 8).toLowerCase())
);

const GITLEAKS_DEDUPED = GITLEAKS_PATTERNS.filter(p => {
  const prefix = p.regex.source.slice(0, 8).toLowerCase();
  return !ORIGINAL_PREFIXES.has(prefix);
});

const API_KEY_PATTERNS = [...ORIGINAL_PATTERNS, ...GITLEAKS_DEDUPED];

// Quick sanity log (remove in production if you prefer clean console)
console.log(`[LLM Guard v3] Loaded ${API_KEY_PATTERNS.length} patterns ` +
  `(${ORIGINAL_PATTERNS.length} original + ${GITLEAKS_DEDUPED.length} from gitleaks)`);

// -------------------------------------------------------
// INLINE STYLES (Shadow DOM isolates from host page CSS)
// -------------------------------------------------------
const OVERLAY_CSS = `
  :host { all: initial; }
  
  #llmguard-root {
    position: fixed;
    top: 0; left: 0; right: 0; bottom: 0;
    background: rgba(0,0,0,0.82);
    backdrop-filter: blur(6px);
    z-index: 2147483647;
    display: flex;
    align-items: center;
    justify-content: center;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    animation: fadeIn 0.18s ease;
  }

  @keyframes fadeIn {
    from { opacity: 0; transform: scale(0.95); }
    to   { opacity: 1; transform: scale(1); }
  }

  .modal {
    background: #0d1117;
    border: 1px solid #30363d;
    border-radius: 14px;
    padding: 28px;
    max-width: 480px;
    width: calc(100% - 40px);
    box-shadow: 0 32px 80px rgba(0,0,0,0.7);
  }

  .header {
    display: flex;
    align-items: flex-start;
    gap: 14px;
    padding-left: 16px;
    margin-bottom: 20px;
    border-left: 4px solid var(--accent, #ff3b3b);
  }

  .shield { font-size: 30px; line-height: 1; }

  .title {
    font-size: 17px;
    font-weight: 700;
    color: #f0f6fc;
    margin: 0 0 4px 0;
  }

  .subtitle {
    font-size: 13px;
    color: #8b949e;
    margin: 0;
  }

  .detections {
    background: #161b22;
    border: 1px solid #21262d;
    border-radius: 8px;
    padding: 12px 14px;
    margin-bottom: 16px;
    display: flex;
    flex-direction: column;
    gap: 9px;
  }

  .det-row {
    display: flex;
    align-items: center;
    gap: 10px;
  }

  .badge {
    font-size: 10px;
    font-weight: 800;
    letter-spacing: 0.07em;
    padding: 3px 8px;
    border-radius: 4px;
    white-space: nowrap;
    text-transform: uppercase;
  }

  .badge-critical { background: rgba(255,59,59,0.18); color: #ff3b3b; border: 1px solid rgba(255,59,59,0.35); }
  .badge-high     { background: rgba(255,140,0,0.15);  color: #ff8c00; border: 1px solid rgba(255,140,0,0.3);  }
  .badge-medium   { background: rgba(240,192,64,0.12); color: #f0c040; border: 1px solid rgba(240,192,64,0.25);}

  .det-name { font-size: 13px; color: #cdd9e5; }

  .message {
    font-size: 13px;
    color: #6e7681;
    line-height: 1.65;
    margin-bottom: 22px;
  }

  .actions {
    display: flex;
    justify-content: flex-end;
    gap: 10px;
  }

  button {
    padding: 9px 20px;
    border-radius: 7px;
    font-size: 13px;
    font-weight: 600;
    cursor: pointer;
    border: none;
    font-family: inherit;
    transition: all 0.15s;
  }

  .btn-dismiss {
    background: #1f6feb;
    color: #fff;
  }
  .btn-dismiss:hover { background: #388bfd; }

  .btn-allow {
    background: transparent;
    color: #6e7681;
    border: 1px solid #30363d !important;
  }
  .btn-allow:hover { color: #ff8c00; border-color: #ff8c00 !important; }

  .footer {
    font-size: 11px;
    color: #30363d;
    margin-top: 16px;
    text-align: center;
  }
`;

const TOAST_CSS = `
  :host { all: initial; }
  #toast {
    position: fixed;
    bottom: 24px;
    right: 24px;
    background: #1c1400;
    border: 1px solid rgba(255,140,0,0.4);
    border-left: 3px solid #ff8c00;
    color: #ffc060;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    font-size: 13px;
    padding: 12px 16px;
    border-radius: 8px;
    z-index: 2147483646;
    max-width: 380px;
    display: flex;
    align-items: center;
    gap: 12px;
    box-shadow: 0 8px 28px rgba(0,0,0,0.5);
    animation: slideIn 0.2s ease;
  }
  @keyframes slideIn {
    from { opacity:0; transform: translateY(10px); }
    to   { opacity:1; transform: translateY(0); }
  }
  button {
    background: none;
    border: none;
    color: #6e7681;
    cursor: pointer;
    font-size: 16px;
    margin-left: auto;
    padding: 0;
    line-height: 1;
  }
`;

// -------------------------------------------------------
// DETECTION
// -------------------------------------------------------
function detectAPIKeys(text) {
  const found = [];
  const seen = new Set();
  for (const p of API_KEY_PATTERNS) {
    if (p.regex.test(text) && !seen.has(p.name)) {
      seen.add(p.name);
      found.push({ name: p.name, severity: p.severity });
    }
  }
  return found;
}

// -------------------------------------------------------
// LOG TO BACKGROUND
// -------------------------------------------------------
function logEvent(type, detections, text) {
  try {
    chrome.runtime.sendMessage({
      type,
      data: {
        detections,
        url: window.location.href,
        hostname: window.location.hostname,
        timestamp: new Date().toISOString(),
        textPreview: text.substring(0, 120).replace(/\n/g, " ")
      }
    });
  } catch(e) {}
}

// -------------------------------------------------------
// SHADOW DOM OVERLAY — immune to host page CSS
// -------------------------------------------------------
function showBlockOverlay(detections, pendingText, targetEl) {
  const oldHost = document.getElementById("llmguard-shadow-host");
  if (oldHost) oldHost.remove();

  const topSeverity = detections.find(d => d.severity === "critical") ? "critical"
                    : detections.find(d => d.severity === "high")     ? "high"
                    : "medium";

  const accentColor = { critical: "#ff3b3b", high: "#ff8c00", medium: "#f0c040" }[topSeverity];

  const host = document.createElement("div");
  host.id = "llmguard-shadow-host";
  host.style.cssText = "all:unset; position:fixed; top:0; left:0; z-index:2147483647;";
  document.documentElement.appendChild(host);

  const shadow = host.attachShadow({ mode: "open" });

  const style = document.createElement("style");
  style.textContent = OVERLAY_CSS;
  shadow.appendChild(style);

  const root = document.createElement("div");
  root.id = "llmguard-root";
  root.style.setProperty("--accent", accentColor);

  root.innerHTML = `
    <div class="modal">
      <div class="header">
        <div class="shield">🛡️</div>
        <div>
          <div class="title">LLM Guard — Paste Blocked</div>
          <div class="subtitle">Sensitive credentials detected in your clipboard</div>
        </div>
      </div>

      <div class="detections">
        ${detections.map(d => `
          <div class="det-row">
            <span class="badge badge-${d.severity}">${d.severity}</span>
            <span class="det-name">${d.name}</span>
          </div>
        `).join("")}
      </div>

      <div class="message">
        This paste was blocked by your company security policy.<br>
        Please remove API keys, tokens, or credentials before sharing with an AI tool.
      </div>

      <div class="actions">
        <button class="btn-dismiss" id="lg-dismiss">Dismiss</button>
        <button class="btn-allow"   id="lg-allow">Allow Anyway (Override)</button>
      </div>

      <div class="footer">LLM Guard • This event has been logged for security review</div>
    </div>
  `;

  shadow.appendChild(root);

  shadow.getElementById("lg-dismiss").addEventListener("click", () => {
    host.remove();
  });

  shadow.getElementById("lg-allow").addEventListener("click", () => {
    host.remove();
    logEvent("OVERRIDE_EVENT", detections, pendingText);

    if (targetEl) {
      targetEl.focus();
      try {
        document.execCommand("insertText", false, pendingText);
      } catch (e) {
        if (targetEl.tagName === "TEXTAREA" || targetEl.tagName === "INPUT") {
          const start = targetEl.selectionStart || 0;
          const end   = targetEl.selectionEnd   || 0;
          const val   = targetEl.value;
          targetEl.value = val.slice(0, start) + pendingText + val.slice(end);
          targetEl.selectionStart = targetEl.selectionEnd = start + pendingText.length;
        } else if (targetEl.isContentEditable) {
          const sel = window.getSelection();
          if (sel.rangeCount) {
            const range = sel.getRangeAt(0);
            range.deleteContents();
            range.insertNode(document.createTextNode(pendingText));
            range.collapse(false);
          } else {
            targetEl.innerText += pendingText;
          }
        }
      }
      targetEl.dispatchEvent(new Event("input",  { bubbles: true }));
      targetEl.dispatchEvent(new Event("change", { bubbles: true }));
    }
  });

  root.addEventListener("click", (e) => {
    if (e.target === root) host.remove();
  });

  setTimeout(() => { if (host.isConnected) host.remove(); }, 20000);
}

// -------------------------------------------------------
// Shadow DOM
// -------------------------------------------------------
function showWarningToast(detections) {
  const oldHost = document.getElementById("llmguard-toast-host");
  if (oldHost) oldHost.remove();

  const host = document.createElement("div");
  host.id = "llmguard-toast-host";
  host.style.cssText = "all:unset; position:fixed; bottom:0; right:0; z-index:2147483646;";
  document.documentElement.appendChild(host);

  const shadow = host.attachShadow({ mode: "open" });

  const style = document.createElement("style");
  style.textContent = TOAST_CSS;
  shadow.appendChild(style);

  const toast = document.createElement("div");
  toast.id = "toast";
  toast.innerHTML = `
    <span>⚠️ LLM Guard: ${detections[0].name} detected in input. Remove before sending.</span>
    <button id="lg-close">✕</button>
  `;
  shadow.appendChild(toast);

  shadow.getElementById("lg-close").addEventListener("click", () => host.remove());
  setTimeout(() => { if (host.isConnected) host.remove(); }, 7000);
}

// -------------------------------------------------------
// PASTE INTERCEPTOR
// -------------------------------------------------------
function setupInterceptor() {
  document.addEventListener("paste", function(e) {
    const text = e.clipboardData?.getData("text/plain") || "";
    if (!text || text.length < 6) return;

    const detections = detectAPIKeys(text);
    if (detections.length === 0) return;

    e.preventDefault();
    e.stopImmediatePropagation();

    logEvent("DETECTION_EVENT", detections, text);
    showBlockOverlay(detections, text, e.target);

  }, true);

  let inputTimer = null;
  document.addEventListener("input", function(e) {
    const el = e.target;
    if (!el) return;
    const value = el.value || el.innerText || el.textContent || "";
    clearTimeout(inputTimer);
    inputTimer = setTimeout(() => {
      const detections = detectAPIKeys(value);
      if (detections.length > 0) {
        logEvent("DETECTION_EVENT", detections, value);
        showWarningToast(detections);
      }
    }, 1000);
  }, true);
}

setupInterceptor();
console.log("[LLM Guard v3] Active →", window.location.hostname);
